/**
 * Replace ImageKit URLs in source files with local paths
 * Uses the mapping generated by migrate-images.js
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const SRC_DIR = path.join(__dirname, "..", "src");
const MAPPING_FILE = path.join(__dirname, "image-mapping.json");

// Load the mapping
const mapping = JSON.parse(fs.readFileSync(MAPPING_FILE, "utf-8"));

function scanFiles(dir, extensions = [".tsx", ".ts"]) {
  let files = [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory() && entry.name !== "node_modules") {
      files = files.concat(scanFiles(fullPath, extensions));
    } else if (extensions.some((ext) => entry.name.endsWith(ext))) {
      files.push(fullPath);
    }
  }
  return files;
}

function main() {
  console.log("=== Replace ImageKit URLs with Local Paths ===\n");

  const files = scanFiles(SRC_DIR);
  let totalReplacements = 0;
  let filesModified = 0;

  // Sort URLs by length (longest first) to avoid partial replacements
  const sortedUrls = Object.keys(mapping).sort((a, b) => b.length - a.length);

  for (const file of files) {
    let content = fs.readFileSync(file, "utf-8");
    const originalContent = content;
    let fileReplacements = 0;

    for (const url of sortedUrls) {
      const localPath = mapping[url];

      // Check if this URL (or variations of it) exists in the file
      if (content.includes(url)) {
        const count = content.split(url).length - 1;
        content = content.replaceAll(url, localPath);
        fileReplacements += count;
      }
    }

    if (fileReplacements > 0) {
      fs.writeFileSync(file, content, "utf-8");
      const relPath = path.relative(path.join(__dirname, ".."), file);
      console.log(`  ${relPath}: ${fileReplacements} replacements`);
      totalReplacements += fileReplacements;
      filesModified++;
    }
  }

  console.log(
    `\nDone! Modified ${filesModified} files with ${totalReplacements} total replacements.`,
  );
}

main();
